### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by nawilliams** [326-queue/project#12]
### We need to add the following information to `docs/proposal.md`
- The team name
- The application name
- The first section titled **Team Overview** including the names of each team member and their github usernames.
- The second section titled **Innovative Idea** which provides a brief paragraph or two describing your application and how it relates to other existing applications. If your application does not relate to an existing application then mention that.
- The third section titled **Important Data** which provides a brief paragraph or two explaining 5 different types of data your application will support/use.
- The fourth section titled **User Interface** which provides a brief paragraph or two explaining the major user interface components of your application along with screenshots of each. You should have at least 5.

**Comment by ikhatri** [comment]
Drafted everything except the UI section. Please see here for clarifications about what the heck this project actually is: https://github.com/326-queue/project/blob/dashboard/docs/proposal.md
