### ISSUE TITLE
Missing spacing between navbar and page body

### ISSUE THREAD

**Issue by nawilliams** [326-queue/project#20]
![image](https://user-images.githubusercontent.com/23364580/46178821-60c92000-c286-11e8-8a54-3ceffa7b20de.png)

**Comment by ikhatri** [comment]
See https://github.com/326-queue/project/pull/18#issuecomment-425288239

**Comment by nawilliams** [comment]
It looks like .page-header also ads a line based on the bootstrap docs. It adds twice as much space as we want, I might just add some padding later.
